# Usa a imagem oficial do Filebeat como base
FROM docker.elastic.co/beats/filebeat:7.11.2

# Copia o seu arquivo de configuração para o local correto dentro do container
COPY filebeat.yml /usr/share/filebeat/filebeat.yml