# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /logs/app.log

# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["es01:9200"]