# Usa uma imagem oficial do Node.js como base
FROM node:14

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o seu arquivo index.js para o container
COPY index.js .

# Comando para iniciar sua aplicação
CMD ["node", "index.js"]